language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"

before_install:
  - pip install pep8

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U pytest

# command to run tests
# TODO: add flake8, pytest
script:
  - pep8 *.py
  - python -m py_compile *.py
  - pytest -v
