language: python
python:
  - "3.6"
  - "3.7"
  - "nightly"

before_install:
  - pip install -r requirements-dev.txt

# command to install dependencies
install:
  - pip install -r requirements.txt

# command to run tests
# Powershell:
# pycodestyle.exe @(gci -path .\*.py, .\parsers\*.py, .\mysql\*.py, .\postgresql\*.py | select -ExpandProperty fullname )
script:
  - pycodestyle *.py
  - pycodestyle discogsxml2db/*.py
  - pycodestyle mysql/*.py
  - pycodestyle postgresql/*.py
  - python -m py_compile *.py
  - pytest -v
